services:
  app:
    image: ghcr.io/loramint/loramint_docker:latest
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - TTN_APP_KEY=${TTN_APP_KEY}
    ports:
      - "8090:8090"
    depends_on:
      - db
    networks:
      - internal

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - internal

networks:
  internal:

volumes:
  db_data:
