services:
  postgres:
    image: postgres:15-alpine
    container_name: loramint_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: loramint
      POSTGRES_USER: loramint
      POSTGRES_PASSWORD: loramint
    ports:
      - "5432:5432"
    volumes:
      - loramint_postgres_data:/var/lib/postgresql/data

volumes:
  loramint_postgres_data:
