name=LoRaMINT
version=0.0.1
author=Matthias Ruf <matthias.ruf@uni-ulm.de>
maintainer=Matthias Ruf <matthias.ruf@uni-ulm.de>
sentence=Programming interface of the sensor component of the measuring system LoRaMINT.
paragraph= LoRaMINT.h - Library for sending Data via LoRaWAN using the Dragino LA66 LoRaWAN Shield in conjunction with TheThingsNetwork and an MariaDB database. All set up like the LoRaMINT-standard. Created by Matthias Ruf in March 2023.
category=Data Processing
url=https://github.com/LoRaMint/LoRaMint.git
architectures=*
depends=Arduino.h, SoftwareSerial.h
dot_a_linkage=false
